import { Benefit } from "./constants"

export const companyBenefits: Benefit[] = [
    {
        title: "Basic Health Insurance",
        description: "Comprehensive health coverage including preventive care, hospitalization, and prescription drugs.",
        provider: "BlueCross BlueShield",
        coverage: "Employee Only",
        type: "Health",
        tag: "Company Provided",
    },
    {
        title: "Basic Dental Insurance",
        description: "Coverage for routine cleanings, exams, and basic dental procedures.",
        provider: "Delta Dental",
        coverage: "Employee Only",
        type: "Dental",
        tag: "Company Provided",
    },
    {
        title: "Basic Life Insurance",
        description: "Life insurance coverage equal to 1x annual salary.",
        provider: "MetLife",
        coverage: "$85,000",
        type: "Life",
        tag: "Company Provided",
    },
    {
        title: "401(k) Retirement Plan",
        description: "Company matches up to 4% of your contributions.",
        provider: "Fidelity",
        coverage: "4% match",
        type: "Retirement",
        tag: "Company Provided",
    },
]

export const optionalBenefits: Benefit[] = [
    {
        title: "Premium Health Insurance",
        description: "Enhanced health coverage with lower deductibles and copays, includes specialist visits.",
        provider: "BlueCross BlueShield",
        coverage: "Employee + Family",
        type: "Health",
        tag: "Optional",
        monthlyCost: 150,
    },
    {
        title: "Family Dental Coverage",
        description: "Extend dental coverage to spouse and dependents.",
        provider: "Delta Dental",
        coverage: "Employee + Family",
        type: "Dental",
        tag: "Optional",
        monthlyCost: 45,
    },
    {
        title: "Vision Insurance",
        description: "Coverage for eye exams, glasses, and contact lenses.",
        provider: "VSP",
        coverage: "Employee Only",
        type: "Vision",
        tag: "Optional",
        monthlyCost: 12,
    },
    {
        title: "Family Vision Insurance",
        description: "Vision coverage for employee and dependents.",
        provider: "VSP",
        coverage: "Employee + Family",
        type: "Vision",
        tag: "Optional",
        monthlyCost: 28,
    },
    {
        title: "Short-term Disability",
        description: "Income protection for temporary disabilities (60% of salary).",
        provider: "Guardian",
        coverage: "60% salary replacement",
        type: "Disability",
        tag: "Optional",
        monthlyCost: 35,
    },
    {
        title: "Long-term Disability",
        description: "Income protection for extended disabilities (60% of salary).",
        provider: "Guardian",
        coverage: "60% salary replacement",
        type: "Disability",
        tag: "Optional",
        monthlyCost: 55,
    },
    {
        title: "Supplemental Life Insurance",
        description: "Additional life insurance up to 5x annual salary.",
        provider: "MetLife",
        coverage: "Up to 5x salary",
        type: "Life",
        tag: "Optional",
        monthlyCost: 25,
    },
    {
        title: "Wellness Program",
        description: "Access to gym memberships, fitness classes, and wellness coaching.",
        provider: "Wellness Corp",
        coverage: "Full access",
        type: "Wellness",
        tag: "Optional",
        monthlyCost: 20,
    },
    {
        title: "Legal Services Plan",
        description: "Legal consultation and document preparation services.",
        provider: "LegalShield",
        coverage: "Unlimited consultations",
        type: "Other",
        tag: "Optional",
        monthlyCost: 18,
    },
    {
        title: "Pet Insurance",
        description: "Health insurance coverage for your pets.",
        provider: "Healthy Paws",
        coverage: "Up to 2 pets",
        type: "Other",
        tag: "Optional",
        monthlyCost: 40,
    },
]