---
name: Renovate

on:
    workflow_dispatch: {}
    schedule:
        - cron: '50 7 * * *'

permissions:
    contents: write
    pull-requests: write
jobs:
    renovate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  persist-credentials: false

            - name: Renovate
              uses: renovatebot/github-action@e09d604f8f803bb527bd8321ed5be06c460b8682 # v46.2.2
              env:
                LOG_LEVEL: info
                RENOVATE_TOKEN: ${{ secrets.RENOVATE_PAT }}
                RENOVATE_REPOSITORIES: ${{ github.repository }}
              with:
                renovate-version: 44.16.1
                configurationFile: .github/renovate.json
