---
name: SBOM Generation

on:
  push:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Generate SBOM (SPDX format)
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        with:
          output-file: sbom.spdx.json
          format: spdx-json
